version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventario_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inventario_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: inventario_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://appuser:apppassword@db:3306/inventario_db"
      PORT: 3000
      JWT_SECRET: "secreto_super_seguro_2026"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: inventario_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      # Sincroniza tu carpeta local del frontend con la raíz del servidor web interno
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data: